### ISSUE TITLE
TypeError: can't convert float to int

### ISSUE THREAD

**Issue by priyamandiga** [nickzoic/mpy-tut#1]
An interesting bug while running the below PWM code from  [motors.rst](https://github.com/nickzoic/mpy-tut/blob/master/motors.rst) on ESP8266.

```
import machine
import time

pin = machine.Pin(2, machine.Pin.OUT)
pwm = machine.PWM(pin)
pwm.freq(1000)

while True:
    for d in range(10,90,10):
        pwm.duty(d/100)
        time.sleep(0.1)
    for d in range(90,10,-10):
        pwm.duty(d/100)
        time.sleep(0.1)
```

When executing ,  TypeError exception is thrown
```Traceback (most recent call last):
  File "<stdin>", line 10, in <module>
TypeError: can't convert float to int
```
Seems that ESP8266 can't handle float-int conversion well.

Wonder if this is an exception w.r.t ESP8266 or underlying wrapper issue ?

**Comment by nickzoic** [comment]
Float to int conversion has to be done explicitly, eg: `int(0.5*1023)` or using an explicit integer division eg: `x//1023` ...

However in this case the real problem is the code is wrong ... duty expects an integer value from 0 to 1023 not a float between 0 and 1 ... fixed, thanks!
