### ISSUE TITLE
pulling the submodule "esp-idf" fails

### ISSUE THREAD

**Issue by mage0r** [nickzoic/mpy-tut#2]
$ git submodule update --init --recursive
fatal: Needed a single revision
Unable to find current revision in submodule path 'esp-idf'

**Comment by nickzoic** [comment]
Thanks for the quick feedback ... this is what I get for launching a thing just as I leave for four days off the Internet :-/.  

Very weird though, it works fine for me ... even pulling a fresh copy with:

```
cd /tmp
git checkout https://github.com/nickzoic/mpy-tut
cd mpy-tut
git submodule update --init --recursive
```

**Comment by nickzoic** [comment]
okay after discussion with @mage0r this seems to be a git client bug at his end, but it is leading me towards maybe scrapping the submodule strategy for this repo ...

**Comment by nickzoic** [comment]
Fixed, although somewhat excessively, by deleting the build submodules in 336758585
I'll improve the build instructions instead.
